apiVersion: pdok.nl/v2beta1
kind: WFS
metadata:
  name: rws-nwbwegen-v1-0
  labels:
    dataset-owner: rws
    dataset: nwbwegen
    service-version: v1_0
    service-type: wfs
  annotations:
    lifecycle-phase: prod
    service-bundle-id: b39c152b-393b-52f5-a50c-e1ffe904b6fb
spec:
  general:
    datasetOwner: rws
    dataset: nwbwegen
    serviceVersion: v1_0
  kubernetes:
    resources:
      limits:
        ephemeralStorage: 505Mi
      requests:
        ephemeralStorage: 255Mi
  service:
    title: NWB - Wegen WFS
    abstract:
      Dit is de web feature service van het Nationaal Wegen Bestand (NWB)
      - wegen. Deze dataset bevat alleen de wegvakken en hectometerpunten. Het Nationaal
      Wegen Bestand - Wegen is een digitaal geografisch bestand van alle wegen in
      Nederland. Opgenomen zijn alle wegen die worden beheerd door wegbeheerders als
      het Rijk, provincies, gemeenten en waterschappen, echter alleen voor zover deze
      zijn voorzien van een straatnaam of nummer.
    inspire: true
    metadataIdentifier: a9fa7fff-6365-4885-950c-e9d9848359ee
    authority:
      name: rws
      url: https://www.rijkswaterstaat.nl
    dataEPSG: EPSG:28992
    extent: -59188.44333693248 304984.64144318487 308126.88473339565 858328.516489961
    keywords:
      - Vervoersnetwerken
      - Menselijke gezondheid en veiligheid
      - Geluidsbelasting hoofdwegen (Richtlijn Omgevingslawaai)
      - Nationaal
      - Voertuigen
      - Verkeer
      - Wegvakken
      - Hectometerpunten
      - HVD
      - Mobiliteit
    featureTypes:
      - name: wegvakken
        title: Wegvakken
        abstract:
          Dit featuretype bevat de wegvakken uit het Nationaal Wegen bestand
          (NWB) en bevat gedetailleerde informatie per wegvak zoals straatnaam, wegnummer,
          routenummer, wegbeheerder, huisnummers, enz.
        sourceMetadataIdentifier: 8f0497f0-dbd7-4bee-b85a-5fdec484a7ff
        datasetMetadataIdentifier: a9b7026e-0a81-4813-93bd-ba49e6f28502
        keywords:
          - Vervoersnetwerken
          - Menselijke gezondheid en veiligheid
          - Geluidsbelasting hoofdwegen (Richtlijn Omgevingslawaai)
          - Nationaal
          - Voertuigen
          - Verkeer
          - Wegvakken
        data:
          gpkg:
            table: wegvakken
            geometryType: MultiLineString
            blobKey: geopackages/rws/nwbwegen/1c56dc48-2cf4-4631-8b09-ed385d5368d1/1/nwb_wegen.gpkg
            columns:
              - fid
              - objectid
              - wvk_id
              - wvk_begdat
              - jte_id_beg
              - jte_id_end
              - wegbehsrt
              - wegnummer
              - wegdeelltr
              - hecto_lttr
              - bst_code
              - rpe_code
              - admrichtng
              - rijrichtng
              - stt_naam
              - stt_bron
              - wpsnaam
              - gme_id
              - gme_naam
              - hnrstrlnks
              - hnrstrrhts
              - e_hnr_lnks
              - e_hnr_rhts
              - l_hnr_lnks
              - l_hnr_rhts
              - begafstand
              - endafstand
              - beginkm
              - eindkm
              - pos_tv_wol
              - wegbehcode
              - wegbehnaam
              - distrcode
              - distrnaam
              - dienstcode
              - dienstnaam
              - wegtype
              - wgtype_oms
              - routeltr
              - routenr
              - routeltr2
              - routenr2
              - routeltr3
              - routenr3
              - routeltr4
              - routenr4
              - wegnr_aw
              - wegnr_hmp
              - geobron_id
              - geobron_nm
              - bronjaar
              - openlr
              - bag_orl
              - frc
              - fow
              - alt_naam
              - alt_nr
              - rel_hoogte
              - st_lengthshape
      - name: hectopunten
        title: Hectopunten
        abstract:
          Dit featuretype bevat de hectopunten uit het Nationaal Wegen Bestand
          (NWB) en bevat gedetailleerde informatie per hectopunt zoals hectometrering,
          afstand, zijde en hectoletter.
        sourceMetadataIdentifier: 8f0497f0-dbd7-4bee-b85a-5fdec484a7ff
        datasetMetadataIdentifier: a9b7026e-0a81-4813-93bd-ba49e6f28502
        keywords:
          - Vervoersnetwerken
          - Menselijke gezondheid en veiligheid
          - Geluidsbelasting hoofdwegen (Richtlijn Omgevingslawaai)
          - Nationaal
          - Voertuigen
          - Verkeer
          - Hectometerpunten
        data:
          gpkg:
            blobKey: geopackages/rws/nwbwegen/1c56dc48-2cf4-4631-8b09-ed385d5368d1/1/nwb_wegen.gpkg
            columns:
              - fid
              - objectid
              - hectomtrng
              - afstand
              - wvk_id
              - wvk_begdat
              - zijde
              - hecto_lttr
            geometryType: MultiPoint
            table: hectopunten
