apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    pdok.nl/app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    pdok.nl/inspire: "false"
    service-type: wms
    service-version: v1_0
  name: noprefetch-wms-mapserver
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WMS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
  annotations:
    "pdok.nl/wms-service-metadata-uuid": "metameta-meta-meta-meta-metametameta"
    uptime.pdok.nl/id: b05a258104b33de6117b1744cd2b8d2231402508
    uptime.pdok.nl/name: NOPREFETCH WMS
    uptime.pdok.nl/tags: public-stats,wms
    uptime.pdok.nl/url: http://localhost:32788/datasetOwner/dataset/wms/v1_0?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=190061.4619730016857,462435.5987861062749,202917.7508707302331,473761.6884966178914&CRS=EPSG:28992&WIDTH=100&HEIGHT=100&LAYERS=layer-name&STYLES=&FORMAT=image/png
spec:
  routes:
    - kind: Rule
      match: Host(`localhost`) && PathPrefix(`/datasetOwner/dataset/wms/v1_0/legend`)
      middlewares:
        - name: noprefetch-wms-mapserver-headers
      services:
        - kind: Service
          name: noprefetch-wms-mapserver
          port: 80
    - kind: Rule
      match: Host(`localhost`) && Path(`/datasetOwner/dataset/wms/v1_0`)
      middlewares:
        - name: noprefetch-wms-mapserver-headers
      services:
        - kind: Service
          name: noprefetch-wms-mapserver
          port: 9111
