apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    pdok.nl/app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    pdok.nl/inspire: "false"
    service-type: wms
    service-version: v1_0
  name: noprefetch-wms-mapserver
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WMS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      pdok.nl/app: mapserver
      dataset: dataset
      dataset-owner: datasetOwner
      pdok.nl/inspire: "false"
      service-type: wms
      service-version: v1_0
