apiVersion: v1
data:
  gpkg_download.sh: "..."
immutable: true
kind: ConfigMap
metadata:
  labels:
    pdok.nl/app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    pdok.nl/inspire: 'false'
    service-type: wfs
    service-version: v1_0
  name: minimal-wfs-init-scripts-fft29bbtdd
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: minimal
      uid: ""
      blockOwnerDeletion: true
      controller: true
