---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pdok-nl-v3-wfs
  failurePolicy: Fail
  name: vwfs-v3.kb.io
  rules:
  - apiGroups:
    - pdok.nl
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    resources:
    - wfs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pdok-nl-v3-wms
  failurePolicy: Fail
  name: vwms-v3.kb.io
  rules:
  - apiGroups:
    - pdok.nl
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    resources:
    - wms
  sideEffects: None
