apiVersion: pdok.nl/v3
kind: WMS
metadata:
  annotations:
    pdok.nl/wms-service-metadata-uuid: metameta-meta-meta-meta-metametameta
  labels:
    dataset: dataset
    dataset-owner: datasetOwner
    service-type: wms
    service-version: v1_0
  name: patches
  namespace: default
spec:
  options: {}
  horizontalPodAutoscalerPatch:
    behavior:
      scaleDown:
        policies:
          - periodSeconds: 30
            type: Pods
            value: 1
        selectPolicy: Min
        stabilizationWindowSeconds: 50
    maxReplicas: 10
    metrics:
      - resource:
          name: memory
          target:
            averageUtilization: 90
            type: Utilization
        type: Resource
    minReplicas: 5
  podSpecPatch:
    restartPolicy: Never
    dnsPolicy: None
    containers:
      - env:
          - name: SERVICE_TYPE
            value: NONE
          - name: MAPSERVER_CONFIG_FILE
            value: "/srv/patch/config"
          - name: MS_MAPFILE
            value: /srv/patch/map.map
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                key: AZURE_STORAGE_CONNECTION_STRING
                name: patch-blobs
          - name: PATCH
            value: PATCH
        image: patch.patch/image:patch
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
                - patch
                - "15"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "patch"
          successThreshold: 10
          failureThreshold: 30
          initialDelaySeconds: 200
          periodSeconds: 100
          timeoutSeconds: 100
        name: mapserver
        terminationMessagePath: /patch/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8000
            protocol: SCTP
          - name: patch
            containerPort: 5000
            protocol: UDP
            hostIP: patch
            hostPort: 5050
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "patch"
          successThreshold: 10
          failureThreshold: 30
          initialDelaySeconds: 200
          periodSeconds: 100
          timeoutSeconds: 100
          terminationGracePeriodSeconds: 1000
        resources:
          limits:
            ephemeral-storage: 4000M
            memory: 8000M
            cpu: "5"
          requests:
            cpu: "5"
            ephemeral-storage: 2000M
            memory: 2000M
        startupProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "patch"
          successThreshold: 10
          failureThreshold: 30
          initialDelaySeconds: 200
          periodSeconds: 100
          timeoutSeconds: 100
        volumeMounts:
          - mountPath: /srv/data/patch
            name: base
            readOnly: true
          - mountPath: /var/www/patch
            name: data
            readOnly: false
            subPath: /patch
          - name: patch
            mountPath: /patch
      - args:
          - "patch"
        image: patch.patch/image:patch
        name: apache-exporter
      - name: ogc-webservice-proxy
        image: patch.patch/image:patch
    initContainers:
      - name: blob-download
        resources:
          requests:
            cpu: '3'
          limits:
            cpu: '5'
      - image: test.test/image:patch5
        imagePullPolicy: Always
        name: capabilities-generator
      - image: test.test/image:patch3
        name: mapfile-generator
        volumeMounts:
          - mountPath: /styling
            name: patch
            readOnly: true
      - image: test.test/image:patch5
        imagePullPolicy: Always
        name: featureinfo-generator
        resources:
          requests:
            memory: '300M'
          limits:
            memory: '500M'
      - command:
          - bash
          - -c
          - |
            patch;
        image: test.test/image:patch
        name: legend-generator
    terminationGracePeriodSeconds: 600
    volumes:
      - configMap:
          name: patch
        name: mapserver
      - name: patch
        csi:
          driver: patch
  service:
    abstract: service-abstract
    accessConstraints: http://creativecommons.org/publicdomain/zero/1.0/deed.nl
    dataEPSG: EPSG:28992
    keywords:
    - service-keyword
    layer:
      abstract: service-abstract
      keywords:
      - service-keyword
      layers:
      - abstract: layer-abstract
        authority:
          name: authority-name
          spatialDatasetIdentifier: bronbron-bron-bron-bron-bronbronbron
          url: http://authority-url
        data:
          gpkg:
            blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file.gpkg
            columns:
            - name: layer-column
            geometryType: Point
            tableName: layer
        datasetMetadataUrl:
          csw:
            metadataIdentifier: datadata-data-data-data-datadatadata
        keywords:
        - layer-keyword
        name: layer-name
        styles:
        - name: layer-style-name
          title: layer-style-title
          visualization: layer-style.style
        title: layer-title
        visible: true
      - abstract: group
        authority:
          name: authority-name
          spatialDatasetIdentifier: src-md-id
          url: http://authority-url
        datasetMetadataUrl:
          csw:
            metadataIdentifier: datadata-data-data-data-datadatadata
        layers:
        - abstract: group-child
          authority:
            name: authority-name
            spatialDatasetIdentifier: src-md-id
            url: http://authority-url
          data:
            gpkg:
              blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file.gpkg
              columns:
              - name: layer-column
              geometryType: Point
              tableName: layer
          datasetMetadataUrl:
            csw:
              metadataIdentifier: datadata-data-data-data-datadatadata
          keywords:
            - layer-keyword
          name: group-child
          styles:
          - name: group-child
            title: group-child
            visualization: layer-style.style
          title: group-child
          visible: true
        keywords:
          - layer-keyword
        name: group
        title: group
        visible: true
      title: service-title
      visible: true
    ownerInfoRef: owner
    stylingAssets:
      configMapRefs:
      - keys:
        - layer-style.style
        name: styling
    title: service-title
    url: http://localhost:32788/datasetOwner/dataset/wms/v1_0