---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pdok.nl
  resources:
  - wfs
  - wms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pdok.nl
  resources:
  - wfs/finalizers
  - wms/finalizers
  verbs:
  - update
- apiGroups:
  - pdok.nl
  resources:
  - wfs/status
  - wms/status
  verbs:
  - get
  - patch
  - update
