apiVersion: pdok.nl/v3
kind: WFS
metadata:
  name: sample
  labels:
    sample: sample
spec:
  podSpecPatch:
    containers:
      - name: mapserver
        resources:
          limits:
            ephemeral-storage: 2G
  service:
    accessConstraints: "http://bla/bla"
    title: "title"
    abstract: "abstract"
    defaultCrs: "EPSG:28992"
    keywords:
      - "keyword"
    ownerInfoRef: "owner"
    prefix: "prefix"
    url: "http://host/path"
    inspire:
      language: dut
      serviceMetadataUrl:
        csw:
          metadataIdentifier: testtest-test-test-test-testtesttest
      spatialDatasetIdentifier: testtest-test-test-test-testtesttest
    featureTypes:
      - name: "name"
        title: "title"
        abstract: "abstract"
        keywords:
          - "word"
        data:
          gpkg:
            blobKey: "container/prefix/file.gpkg"
            columns:
              - name: "column"
            geometryType: "Point"
            tableName: "table"
