apiVersion: pdok.nl/v3
kind: WFS
metadata:
  labels:
    app.kubernetes.io/name: mapserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: wfs-sample
spec:
  # TODO(user): Add fields here
