apiVersion: v1
data:
  default_mapserver.conf: ...
  input: |-
    "layer-name" "layer-style-name"
    "group" "group"
    "group-child" "group-child"
immutable: true
kind: ConfigMap
metadata:
  labels:
    app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    inspire: "false"
    service-type: wms
    service-version: v1_0
  name: custom-mapfile-wms-legend-generator-6cf9f5k5h5
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WMS
      name: custom-mapfile
      uid: ""
      blockOwnerDeletion: true
      controller: true
