apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    inspire: true
    service-type: wfs
    service-version: v1_0
    theme: theme
  name: complete-wfs-mapserver
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: complete
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mapserver
      dataset: dataset
      dataset-owner: datasetOwner
      inspire: true
      service-type: wfs
      service-version: v1_0
      theme: theme
