apiVersion: pdok.nl/v3
kind: WMS
metadata:
  annotations:
    pdok.nl/wms-service-metadata-uuid: metameta-meta-meta-meta-metametameta
  labels:
    dataset: dataset
    dataset-owner: datasetOwner
    service-type: wms
    service-version: v1_0
  name: custom-mapfile
  namespace: default
spec:
  options: {}
  podSpecPatch:
    initContainers:
      - name: blob-download
        envFrom:
          - configMapRef:
              name: blobs-testtest
          - secretRef:
              name: blobs-testtest
    containers:
      - name: mapserver
        env:
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                key: AZURE_STORAGE_CONNECTION_STRING
                name: blobs-testtest
        resources:
          limits:
            ephemeral-storage: 100m
  service:
    prefix: dataset
    abstract: service-abstract
    accessConstraints: http://creativecommons.org/publicdomain/zero/1.0/deed.nl
    dataEPSG: EPSG:28992
    keywords:
    - service-keyword
    layer:
      abstract: service-abstract
      keywords:
      - service-keyword
      boundingBoxes:
        - bbox:
            maxx: "280000"
            maxy: "860000"
            minx: "-25000"
            miny: "250000"
          crs: EPSG:28992
      layers:
      - abstract: layer-abstract
        authority:
          name: authority-name
          spatialDatasetIdentifier: bronbron-bron-bron-bron-bronbronbron
          url: http://authority-url
        data:
          gpkg:
            blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file.gpkg
            columns:
            - name: layer-column
            geometryType: Point
            tableName: layer
        datasetMetadataUrl:
          csw:
            metadataIdentifier: datadata-data-data-data-datadatadata
        keywords:
        - layer-keyword
        name: layer-name
        styles:
        - name: layer-style-name
          title: layer-style-title
        title: layer-title
        visible: true
      - abstract: group
        authority:
          name: authority-name
          spatialDatasetIdentifier: src-md-id
          url: http://authority-url
        datasetMetadataUrl:
          csw:
            metadataIdentifier: datadata-data-data-data-datadatadata
        layers:
        - abstract: group-child
          authority:
            name: authority-name
            spatialDatasetIdentifier: src-md-id
            url: http://authority-url
          data:
            gpkg:
              blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file.gpkg
              columns:
              - name: layer-column
              geometryType: Point
              tableName: layer
          datasetMetadataUrl:
            csw:
              metadataIdentifier: datadata-data-data-data-datadatadata
          keywords:
            - layer-keyword
          name: group-child
          styles:
          - name: group-child
            title: group-child
          - name: style
            title: style
          title: group-child
          visible: true
        keywords:
          - layer-keyword
        name: group
        title: group
        visible: true
        styles:
          - name: style
            title: style
      title: service-title
      visible: true
    mapfile:
      configMapKeyRef:
        name: configMap
        key: mapfile.map
    ownerInfoRef: owner
    title: service-title
    url: http://localhost:32788/datasetOwner/dataset/wms/v1_0