apiVersion: v1
data:
  input.yaml: "..."
immutable: true
kind: ConfigMap
metadata:
  labels:
    pdok.nl/app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    pdok.nl/inspire: 'false'
    service-type: wfs
    service-version: v1_0
  name: noprefetch-wfs-capabilities-generator-tk7t48fd89
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
