apiVersion: v1
data:
  input.json: "..."
immutable: true
kind: ConfigMap
metadata:
  labels:
    app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    inspire: 'false'
    service-type: wfs
    service-version: v1_0
  name: noprefetch-wfs-mapfile-generator-g82gh74ddd
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
