---
apiVersion: v1
data:
  default_mapserver.conf: "..."
  include.conf: "..."
  ogc.lua: "..."
  scraping-error.xml: "..."
immutable: true
kind: ConfigMap
metadata:
  labels:
    app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    inspire: "false"
    service-type: wfs
    service-version: v1_0
  name: noprefetch-wfs-mapserver-f5ch9b2bhh
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
