apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mapserver
    dataset: dataset
    dataset-owner: datasetOwner
    inspire: 'false'
    service-type: wfs
    service-version: v1_0
  name: noprefetch-wfs-mapserver
  namespace: default
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: WFS
      name: noprefetch
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mapserver
      dataset: dataset
      dataset-owner: datasetOwner
      inspire: 'false'
      service-type: wfs
      service-version: v1_0
