apiVersion: pdok.nl/v3
kind: WFS
metadata:
  labels:
    dataset: dataset
    dataset-owner: datasetOwner
    service-type: wfs
    service-version: v1_0
    theme: theme
  name: complete
  namespace: default
spec:
  ingressRouteUrls:
    - url: http://localhost:32788/datasetOwner/dataset/theme/wfs/v1_0
    - url: http://localhost:32788/other/path
  healthCheck:
    querystring: test=123
    mimetype: text/html
  horizontalPodAutoscalerPatch:
    maxReplicas: 50
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 20
          type: Utilization
      type: Resource
    minReplicas: 1
  options: {}
  podSpecPatch:
    containers:
    - name: mapserver
      resources:
        limits:
          cpu: "2"
          ephemeral-storage: 11G
          memory: 500M
        requests:
          cpu: "1"
          ephemeral-storage: 11G
          memory: 250M
  service:
    abstract: some "Service" abstract
    accessConstraints: http://creativecommons.org/publicdomain/zero/1.0/deed.nl
    bbox:
      defaultCRS:
        maxx: "3"
        maxy: "4"
        minx: "1"
        miny: "2"
    defaultCrs: EPSG:28992
    featureTypes:
    - abstract: feature "1" abstract
      bbox:
        defaultCRS:
          maxx: "3"
          maxy: "4"
          minx: "1"
          miny: "2"
      data:
        gpkg:
          blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file-1.gpkg
          columns:
          - name: featuretype-1-column-1
          - name: featuretype-1-column-2
          geometryType: Point
          tableName: featuretype-1
      datasetMetadataUrl:
        csw:
          metadataIdentifier: datadata-data-data-data-datadatadata
      keywords:
      - featuretype-1-keyword-1
      - featuretype-1-keyword-2
      name: featuretype-1-name
      title: feature "1" title
    - abstract: feature "2" abstract
      bbox:
        defaultCRS:
          maxx: "7"
          maxy: "8"
          minx: "5"
          miny: "6"
      data:
        gpkg:
          blobKey: ${BLOBS_GEOPACKAGES_BUCKET}/key/file-2.gpkg
          columns:
          - alias: ALIAS_featuretype-2-column-1
            name: featuretype-2-column-1
          - name: featuretype-2-column-2
          geometryType: MultiLineString
          tableName: featuretype-2
      datasetMetadataUrl:
        csw:
          metadataIdentifier: datadata-data-data-data-datadatadata
      keywords:
      - featuretype-2-keyword-1
      - featuretype-2-keyword-2
      name: featuretype-2-name
      title: feature "2" title
    - abstract: featuretype-3-abstract
      bbox:
        defaultCRS:
          maxx: "9"
          maxy: "0"
          minx: "1"
          miny: "2"
      data:
        postgis:
          columns:
          - name: featuretype-3-column-1
          - name: featuretype-3-column-2
          geometryType: MultiLineString
          tableName: featuretype-3
      datasetMetadataUrl:
        csw:
          metadataIdentifier: datadata-data-data-data-datadatadata
      keywords:
      - featuretype-3-keyword-1
      - featuretype-3-keyword-2
      name: featuretype-3-name
      title: featuretype-3-title
    inspire:
      language: dut
      serviceMetadataUrl:
        csw:
          metadataIdentifier: metameta-meta-meta-meta-metametameta
      spatialDatasetIdentifier: bronbron-bron-bron-bron-bronbronbron
    keywords:
    - service-keyword-1
    - service-keyword-2
    otherCrs:
    - EPSG::25831
    - EPSG::25832
    - EPSG::3034
    - EPSG::3035
    - EPSG::3857
    - EPSG::4258
    - EPSG::4326
    ownerInfoRef: owner
    prefix: dataset
    title: some Service title
    url: http://localhost:32788/datasetOwner/dataset/theme/wfs/v1_0
