apiVersion: pdok.nl/v3
kind: WFS
metadata:
  labels:
    app.kubernetes.io/name: mapserver-operator
    app.kubernetes.io/managed-by: kustomize
    dataset: dataset
    dataset-owner: eigenaar
    service-type: wfs
    service-version: 1.0.0
  name: sample-v3
spec:
  lifecycle:
    ttlInDays: 21
  podSpecPatch:
    containers:
      - name: mapserver
        resources:
          limits:
            memory: 12M
            ephemeral-storage: 2G
  horizontalPodAutoscalerPatch:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: wfs-sample-v3
    maxReplicas: 5
    minReplicas: 2
    metrics:
      - type: "Resource"
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
  options:
    automaticCasing: true
    prefetchData: false
    includeIngress: false
  service:
    prefix: ""
    url: https://service.pdok.nl/eigenaar/dataset/wfs/1.0.0
    inspire:
      serviceMetadataUrl:
        csw:
          metadataIdentifier: 68a42961-ed55-436b-a412-cc7424fd2a6e
      spatialDatasetIdentifier: ""
      language: "dut"
    ownerInfoRef: pdok
    title: "Dataset"
    abstract: "Dataset beschrijving ..."
    keywords:
      - keyword1
      - keyword2
    fees: ""
    accessConstraints: ""
    defaultCrs: "EPSG:28992"
    bbox:
      defaultCRS:
        minx: "0"
        maxx: "280000"
        miny: "300000"
        maxy: "625000"
    countDefault: "12"
    featureTypes:
      - name: FeatureType1
        title: FeatureType1
        abstract: "FeatureType 1 beschrijving..."
        keywords:
          - keyword1
          - keyword2
        datasetMetadataUrl:
          csw:
            metadataIdentifier: 07d73b60-dfd6-4c54-9c82-9fac70c6c48e
        bbox:
          defaultCRS: # EXTENT/wfs_extent in mapfile
            minx: "0"
            maxx: "280000"
            miny: "300000"
            maxy: "625000"
        data:
          gpkg:
            blobKey: eigenaar/dataset/data.gpkg
            tableName: table1
            geometryType: "MultiPolygon"
            columns:
              - name: naam
              - name: gebiedsnum
                alias: gebiedsnummer
              - name: besluitnum
              - name: besluitdat
                alias: datum
      - name: FeatureType2
        title: FeatureType2
        abstract: "FeatureType 2 beschrijving..."
        keywords:
          - keyword1
          - keyword2
        datasetMetadataUrl:
          csw:
            metadataIdentifier: 07d73b60-dfd6-4c54-9c82-9fac70c6c48f
        bbox:
          defaultCRS: # EXTENT/wfs_extent in mapfile
            minx: "0"
            maxx: "280000"
            miny: "300000"
            maxy: "625000"
        data:
          gpkg:
            blobKey: eigenaar/dataset/data.gpkg
            tableName: table2
            geometryType: "MultiPolygon"
            columns:
              - name: naam
              - name: gebiedsnum
                alias: gebiedsnummer
              - name: besluitnum
              - name: besluitdat
                alias: datum