apiVersion: pdok.nl/v3
kind: WMS
metadata:
  labels:
    app.kubernetes.io/name: mapserver-operator
    app.kubernetes.io/managed-by: kustomize
    dataset: dataset
    dataset-owner: owner
    service-type: wms
    service-version: 1.0.0
  name: sample-v3
spec:
  options:
    automaticCasing: true
  lifecycle:
    ttlInDays: 21
  podSpecPatch:
    containers:
      - name: mapserver
        resources:
          limits:
            memory: 12M
            ephemeral-storage: 2G
  horizontalPodAutoscalerPatch:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: wms-sample-v3
    maxReplicas: 5
    minReplicas: 2
    metrics:
      - type: "Resource"
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 120
  service:
    url: https://service.pdok.nl/owner/dataset/wms/1.0.0
    title: "Dataset"
    abstract: "Dataset abstract ..."
    keywords:
      - keyword1
      - keyword2
    ownerInfoRef:
    fees: "test"
    accessConstraints: "http://creativecommons.org/publicdomain/zero/1.0/deed.nl"
    maxSize:
    inspire:
      serviceMetadataUrl:
        csw:
          metadataIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
      spatialDatasetIdentifier: abcd1234-abcd-1234-abcd-1234abcd1234
      language: "nl"
    dataEPSG: EPSG:28992
    resolution:
    defResolution:
    stylingAssets:
    mapfile:
    layer:
      name: top-layer-name
      title: Top "Layer" Title
      abstract: Top "Layer" Abstract
      keywords:
        - top-layer-keyword-1
        - top-layer-keyword-2
      boundingBoxes:
        - crs: EPSG:28992
          bbox:
            minx: "482.06"
            maxx: "306602.42"
            miny: "284182.97"
            maxy: "637049.52"
      visible: true
      authority:
        name: "test"
        url: "https://test.com"
        spatialDatasetIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
      datasetMetadataUrl:
        csw:
          metadataIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
      minscaledenominator:
      maxscaledenominator:
      styles:
        - title: style-title-1
          name: style-name-1
          abstract: Style abstract 1
          visualization: style-1.style
          legend:
            width: 50
            height: 150
            format: png
            blobKey: resources-bucket/key/style-1-legend.png
      labelNoClip: false
      data:
      layers:
        - name: group-layer-name
          title: Group "Layer" Title
          abstract: Group "Abstract" Abstract
          keywords:
            - group-layer-keyword-1
            - group-layer-keyword-2
          boundingBoxes:
          visible: true
          authority:
            name: "test"
            url: "https://test.com"
            spatialDatasetIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
          datasetMetadataUrl:
            csw:
              metadataIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
          minscaledenominator:
          maxscaledenominator:
          styles:
            - title: style-title-2
              name: style-name-2
              abstract: Style abstract 2
              visualization: style-2.style
              legend:
                width: 50
                height: 150
                format: png
                blobKey: resources-bucket/key/style-2-legend.png
          labelNoClip: false
          layers:
            - name: gpkg-layer-name
              title: GPKG "Layer" Title
              abstract: GPKG "Abstract" Abstract
              keywords:
                - gpkg-layer-keyword-1
                - gpkg-layer-keyword-2
              boundingBoxes:
              visible: true
              authority:
                name: "test"
                url: "https://test.com"
                spatialDatasetIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
              datasetMetadataUrl:
                csw:
                  metadataIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
              minscaledenominator:
              maxscaledenominator:
              styles:
                - name: gpkg-layer-style-name
                  title: gpkg-layer-style-title
                  abstract: Gpkg layer style abstract
                  visualization: gpkg-layer-style.style
                  legend:
                    width: 50
                    height: 150
                    format: png
                    blobKey: resources-bucket/key/gpkg-layer-style-legend.png
              labelNoClip: false
              data:
                gpkg:
                  blobKey: "geopackages-bucket/key/gpkg-layer-data.gpkg"
                  tableName: "table-1"
                  geometryType: "MultiPolygon"
                  columns:
                    - name: "column-1"
                      alias: "alias-column-1"
                    - name: "column-2"
                    - name: "column-3"
                      alias: "alias-column-3"
            - name: tif-layer-name
              title: TIF "Layer" Title
              abstract: TIF "Abstract" Abstract
              keywords:
                - tif-layer-keyword-1
                - tif-layer-keyword-2
              boundingBoxes:
              visible: true
              authority:
                name: "test"
                url: "https://test.com"
                spatialDatasetIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
              datasetMetadataUrl:
                csw:
                  metadataIdentifier: 1234abcd-1234-abcd-1234-abcd1234abcd
              minscaledenominator:
              maxscaledenominator:
              styles:
                - name: tif-layer-style-name
                  title: tif-layer-style-title
                  abstract: TIF layer style abstract
                  visualization: tif-layer-style.style
                  legend:
                    width: 50
                    height: 150
                    format: png
                    blobKey: resources-bucket/key/tif-layer-style-legend.png
              labelNoClip: false
              data:
                tif:
                  blobKey: "tifs-bucket/key/tif-layer-data.tif"
                  offsite: "#FF00FF"
                  resample: "AVERAGE"
                  getFeatureInfoIncludesClass: true
